<a href="graph.php?cinta=1">januari</a> <br><br>
<a href="graph.php?cinta=2">februari</a> <br><br>
<a href="graph.php?cinta=3">maret</a> <br><br>
<a href="graph.php?cinta=4">april</a> <br><br>
<a href="graph.php?cinta=5">mei</a> <br><br>
<a href="graph.php?cinta=6">juni</a> <br><br>
<a href="graph.php?cinta=7">juli</a> <br><br>
<a href="graph.php?cinta=8">agustus</a> <br><br>
<a href="graph.php?cinta=9">september</a> <br><br>
<a href="graph.php?cinta=10">oktober</a> <br><br>
<a href="graph.php?cinta=11">november</a> <br><br>
<a href="graph.php?cinta=13">desember</a> <br><br>
